version: '3.8'

services:
  # --- Discovery Server (The "Receptionist") ---
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-network

  # --- PostgreSQL Database ---
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - micro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Product Microservice ---
  # --- Instance Spain ---
  product-es:
    build: ./Product
    container_name: product-es
    ports:
      - "8080:8080" # Local access via 8080
      - "5005:5005" # Debug access via 5005
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - COUNTRY_CODE=ES
      - COUNTRY_NAME=Spain
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#      This line enabled debug mode for Intellij
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - micro-network
    depends_on:
      postgres-db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  # --- Instance UNITED KINGDOM ---
  product-uk:
    build: ./Product
    container_name: product-uk
    ports:
      - "8082:8080"
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - COUNTRY_CODE=uk
      - COUNTRY_NAME=United Kingdom
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - micro-network
    depends_on:
      - postgres-db
      - eureka-server

  # --- Instance USA ---
  product-us:
    build: ./Product
    container_name: product-us
    ports:
      - "8083:8080"
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - COUNTRY_CODE=US
      - COUNTRY_NAME=United States
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - micro-network
    depends_on:
      - postgres-db
      - eureka-server

  # --- Instance CHINA ---
  product-cn:
    build: ./Product
    container_name: product-cn
    ports:
      - "8084:8080"
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - COUNTRY_CODE=CN
      - COUNTRY_NAME=China
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - micro-network
    depends_on:
      - postgres-db
      - eureka-server

  # --- Item Microservice ---
  item-service:
    build: ./Item
    container_name: item-service
    ports:
      - "8081:8081"
      - "5006:5005" # Debug access via 5006
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - PRODUCT_SERVICE_URL=http://product-service/api/v1/products
#This line enabled debug mode for Intellij
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - micro-network
    depends_on:
      eureka-server:
        condition: service_started
      # Update these to match your new instance names
      product-es:
        condition: service_started
      product-uk:
        condition: service_started
      product-us:
        condition: service_started
      product-cn:
        condition: service_started

networks:
  micro-network:
    driver: bridge

volumes:
  postgres_data:
