version: '3.8'

services:
  # --- Discovery Server (The "Receptionist") ---
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-network

  # --- PostgreSQL Database ---
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - micro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Product Microservice ---
  product-service:
    build: ./Product
    container_name: product-service
    # We don't expose port 8080 externally if we want everything to go through Item or Gateway
    # But we leave it for now for your tests
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - micro-network
    depends_on:
      postgres-db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  # --- Item Microservice ---
  item-service:
    build: ./Item
    container_name: item-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - PRODUCT_SERVICE_URL=http://product-service/api/v1/products
    networks:
      - micro-network
    depends_on:
      product-service:
        condition: service_started
      eureka-server:
        condition: service_started

networks:
  micro-network:
    driver: bridge

volumes:
  postgres_data:
